---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#

# Default: "your-hostname" A human-readable display name that identifies this Kibana instance.
server.name: emzil-kibana

# Default: "localhost" This setting specifies the host of the back end server.
server.host: emzil-kibana

# Default: 5601 Kibana is served by a back end server. This setting specifies the port to use.
#server.port: 5601

# Default: ".kibana" Kibana uses an index in Elasticsearch to store saved searches, visualizations and dashboards.
# Kibana creates a new index if the index doesn’t already exist.
# If you configure a custom index, the name must be lowercase, and conform to Elasticsearch index name limitations:
# https://www.elastic.co/guide/en/elasticsearch/reference/7.0/indices-create-index.html
kibana.index: kibana

# Default: "http://localhost:9200" The URLs of the Elasticsearch instances to use for all your queries.
# All nodes listed here must be on the same cluster.
elasticsearch.hosts: 'http://emzil-elastic-01:9200'

# Logs queries sent to Elasticsearch. Requires logging.verbose set to true.
# This is useful for seeing the query DSL generated by applications that currently do not have an inspector,
# for example Timelion and Monitoring.
elasticsearch.logQueries: 'false'

# When this setting’s value is true, Kibana uses the hostname specified in the server.host setting.
# When the value of this setting is false, Kibana uses the hostname of the host that connects to this Kibana instance.
elasticsearch.preserveHost: 'true'

# Default: stdout Enables you specify a file where Kibana stores log output.
#logging.dest: stdout

#Default: false Logs output as JSON.
# When set to true, the logs will be formatted as JSON strings that include timestamp, log level, context,
# message text and any other metadata that may be associated with the log message itself.
# If logging.dest.stdout is set and there is no interactive terminal ("TTY"), this setting will default to true.
logging.json: 'false'

# Set the value of this setting to true to suppress all logging output other than error messages.
logging.quiet: 'false'

# Set the value of this setting to true to suppress all logging output.
logging.silent: 'false'

# Default: UTC Set to the canonical timezone id (for example, America/Los_Angeles) to log events using that timezone.
# A list of timezones can be referenced at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
logging.timezone: Asia/Tehran

# Default: false Set the value of this setting to true to log all events, including system usage information and all requests.
# Supported on Elastic Cloud Enterprise.
logging.verbose: 'false'

